// generated by goxsd; DO NOT EDIT

package models

// Navetavisering is generated from an XSD element
type Navetavisering struct {
	Aviseringsinformation Aviseringsinformation `xml:"Aviseringsinformation"`
	Folkbokforingsposter  Folkbokforingsposter  `xml:"Folkbokforingsposter"`
}

// Aviseringsinformation is generated from an XSD element
type Aviseringsinformation struct {
	Medieleverantor Medieleverantor `xml:"Medieleverantor"`
	Mediemottagare  Mediemottagare  `xml:"Mediemottagare"`
	Filinformation  Filinformation  `xml:"Filinformation"`
}

// Medieleverantor is generated from an XSD element
type Medieleverantor struct {
}

// Mediemottagare is generated from an XSD element
type Mediemottagare struct {
	KundNr     string `xml:"KundNr"`
	SlutKundNr string `xml:"SlutKundNr"`
}

// Filinformation is generated from an XSD element
type Filinformation struct {
	BestallningsID  string `xml:"BestallningsId"`
	Filtyp          string `xml:"Filtyp"`
	Bestallningstyp string `xml:"Bestallningstyp"`
	Produkt         string `xml:"Produkt"`
	Utfil           Utfil  `xml:"Utfil"`
}

// Utfil is generated from an XSD element
type Utfil struct {
	Filnamn                string `xml:"Filnamn"`
	Effektueringsdatum     int    `xml:"Effektueringsdatum"`
	AntalPoster            int    `xml:"AntalPoster"`
	AntalPosterTotalt      int    `xml:"AntalPosterTotalt"`
	AntalFiler             int    `xml:"AntalFiler"`
	FilNr                  int    `xml:"FilNr"`
	Filtitel               string `xml:"Filtitel"`
	JobbID                 int    `xml:"JobbId"`
	LopNr                  int    `xml:"LopNr"`
	FilnamnInfilTillGrund  string `xml:"FilnamnInfilTillGrund"`
	UtsokningsdatumFromTom string `xml:"UtsokningsdatumFromTom"`
}

// Folkbokforingsposter is generated from an XSD element
type Folkbokforingsposter struct {
	Folkbokforingspost []Folkbokforingspost `xml:"Folkbokforingspost"`
}

// Folkbokforingspost is generated from an XSD element
type Folkbokforingspost struct {
	Sekretessmarkering   string        `xml:"Sekretessmarkering"`
	SkyddadFolkbokforing string        `xml:"SkyddadFolkbokforing"`
	Arendeuppgift        Arendeuppgift `xml:"Arendeuppgift"`
	Personpost           Personpost    `xml:"Personpost"`
	Historik             Historik      `xml:"Historik"`
	Sarlosning           Sarlosning    `xml:"Sarlosning"`
}

// Arendeuppgift is generated from an XSD element
type Arendeuppgift struct {
	Andringstidpunkt int    `xml:"andringstidpunkt,attr"`
	Totalpost        string `xml:"totalpost,attr"`
	Utsokningsdatum  string `xml:"utsokningsdatum,attr"`
	PostID           string `xml:"PostId"`
	Arendetyp        string `xml:"Arendetyp"`
}

// Personpost is generated from an XSD element
type Personpost struct {
	PersonID                   PersonID                   `xml:"PersonId"`
	HanvisningsPersonNr        int                        `xml:"HanvisningsPersonNr"`
	Hanvisningar               Hanvisningar               `xml:"Hanvisningar"`
	Avregistrering             Avregistrering             `xml:"Avregistrering"`
	Fodelsedatum               int                        `xml:"Fodelsedatum"`
	Namn                       Namn                       `xml:"Namn"`
	Folkbokforing              Folkbokforing              `xml:"Folkbokforing"`
	Adresser                   Adresser                   `xml:"Adresser"`
	Civilstand                 Civilstand                 `xml:"Civilstand"`
	Fodelse                    Fodelse                    `xml:"Fodelse"`
	Invandring                 Invandring                 `xml:"Invandring"`
	Relationer                 Relationer                 `xml:"Relationer"`
	Medborgarskap              []Medborgarskap            `xml:"Medborgarskap"`
	Samordningsnummeruppgifter Samordningsnummeruppgifter `xml:"Samordningsnummeruppgifter"`
}

// PersonID is generated from an XSD element
type PersonID struct {
	IDentitetsstatus    IDentitetsstatus `xml:"Identitetsstatus"`
	IDentitetsniva      string           `xml:"Identitetsniva"`
	IDentitetsnivadatum int              `xml:"Identitetsnivadatum"`
}

// IDentitetsstatus is generated from an XSD element
type IDentitetsstatus struct {
	IDentitetsstatusVarde string `xml:"IdentitetsstatusVarde"`
	IDentitetsstatusDatum int    `xml:"IdentitetsstatusDatum"`
	IDentitetsstatusOrsak string `xml:"IdentitetsstatusOrsak"`
}

// Hanvisningar is generated from an XSD element
type Hanvisningar struct {
	Hanvisning []Hanvisning `xml:"Hanvisning"`
}

// Hanvisning is generated from an XSD element
type Hanvisning struct {
	Status            string  `xml:"status,attr"`
	HanvisningsPersonNr int `xml:"HanvisningsPersonNr"`
}

// Avregistrering is generated from an XSD element
type Avregistrering struct {
	AvregistreringsorsakKod string `xml:"AvregistreringsorsakKod"`
	Avregistreringsdatum    int    `xml:"Avregistreringsdatum"`
	AntraffadDod            int    `xml:"AntraffadDod"`
}

// Namn is generated from an XSD element
type Namn struct {
	Tilltalsnamnsmarkering int    `xml:"Tilltalsnamnsmarkering"`
	Fornamn                string `xml:"Fornamn"`
	Mellannamn             string `xml:"Mellannamn"`
	Efternamn              string `xml:"Efternamn"`
	Aviseringsnamn         string `xml:"Aviseringsnamn"`
}

// Folkbokforing is generated from an XSD element
type Folkbokforing struct {
	Folkbokforingsdatum  int    `xml:"Folkbokforingsdatum"`
	LanKod               string `xml:"LanKod"`
	KommunKod            string `xml:"KommunKod"`
	ForsamlingKod        string `xml:"ForsamlingKod"`
	Fastighetsbeteckning string `xml:"Fastighetsbeteckning"`
	Trappuppgang         string `xml:"Trappuppgang"`
	Lagenhet             string `xml:"Lagenhet"`
	FiktivtNr            int    `xml:"FiktivtNr"`
	Folkbokforingstyp    string `xml:"Folkbokforingstyp"`
}

// Adresser is generated from an XSD element
type Adresser struct {
	Folkbokforingsadress Folkbokforingsadress `xml:"Folkbokforingsadress"`
	Riksnycklar          Riksnycklar          `xml:"Riksnycklar"`
	UUID                 UUID                 `xml:"UUID"`
	Distrikt             Distrikt             `xml:"Distrikt"`
	SarskildPostadress   SarskildPostadress   `xml:"SarskildPostadress"`
	Utlandsadress        Utlandsadress        `xml:"Utlandsadress"`
}

// Folkbokforingsadress is generated from an XSD element
type Folkbokforingsadress struct {
	CareOf            string `xml:"CareOf"`
	Utdelningsadress1 string `xml:"Utdelningsadress1"`
	Utdelningsadress2 string `xml:"Utdelningsadress2"`
	PostNr            int    `xml:"PostNr"`
	Postort           string `xml:"Postort"`
}

// Riksnycklar is generated from an XSD element
type Riksnycklar struct {
	FastighetsID  string `xml:"FastighetsId"`
	AdressplatsID int    `xml:"AdressplatsId"`
	LagenhetsID   int    `xml:"LagenhetsId"`
}

// UUID is generated from an XSD element
type UUID struct {
	Fastighet string `xml:"Fastighet"`
	Adress    string `xml:"Adress"`
	Lagenhet  string `xml:"Lagenhet"`
}

// Distrikt is generated from an XSD element
type Distrikt struct {
	Distriktskod int `xml:"Distriktskod"`
}

// SarskildPostadress is generated from an XSD element
type SarskildPostadress struct {
	CareOf            string `xml:"CareOf"`
	Utdelningsadress1 string `xml:"Utdelningsadress1"`
	Utdelningsadress2 string `xml:"Utdelningsadress2"`
	PostNr            int    `xml:"PostNr"`
	Postort           string `xml:"Postort"`
}

// Utlandsadress is generated from an XSD element
type Utlandsadress struct {
	Utdelningsadress1  string `xml:"Utdelningsadress1"`
	Utdelningsadress2  string `xml:"Utdelningsadress2"`
	Utdelningsadress3  string `xml:"Utdelningsadress3"`
	Land               string `xml:"Land"`
	Utlandsadressdatum int    `xml:"Utlandsadressdatum"`
	Rostrattsdatum     int    `xml:"Rostrattsdatum"`
}

// Civilstand is generated from an XSD element
type Civilstand struct {
	CivilstandKod    string `xml:"CivilstandKod"`
	Civilstandsdatum int    `xml:"Civilstandsdatum"`
}

// Fodelse is generated from an XSD element
type Fodelse struct {
	HemortSverige HemortSverige `xml:"HemortSverige"`
	OrtUtlandet   OrtUtlandet   `xml:"OrtUtlandet"`
}

// HemortSverige is generated from an XSD element
type HemortSverige struct {
	FodelselanKod     string `xml:"FodelselanKod"`
	Fodelseforsamling string `xml:"Fodelseforsamling"`
}

// OrtUtlandet is generated from an XSD element
type OrtUtlandet struct {
	FodelseortUtland string `xml:"FodelseortUtland"`
	Fodelseland      string `xml:"Fodelseland"`
}

// Invandring is generated from an XSD element
type Invandring struct {
	Invandringsdatum int    `xml:"Invandringsdatum"`
	Uppehallsratt    string `xml:"Uppehallsratt"`
	NordisktPnrDa    string `xml:"NordisktPnrDa"`
	NordisktPnrFi    string `xml:"NordisktPnrFi"`
	NordisktPnrFo    string `xml:"NordisktPnrFo"`
	NordisktPnrIs    string `xml:"NordisktPnrIs"`
	NordisktPnrNo    string `xml:"NordisktPnrNo"`
}

// Relationer is generated from an XSD element
type Relationer struct {
	Relation []Relation `xml:"Relation"`
}

// Relation is generated from an XSD element
type Relation struct {
	Status            string `xml:"status,attr"`
	RelationID        RelationID     `xml:"RelationId"`
	Relationstyp      string         `xml:"Relationstyp"`
	RelationFromdatum int            `xml:"RelationFromdatum"`
	RelationTomdatum  int            `xml:"RelationTomdatum"`
	Namn              Namn           `xml:"Namn"`
	Avregistrering    Avregistrering `xml:"Avregistrering"`
}

// RelationID is generated from an XSD element
type RelationID struct {
}

// Medborgarskap is generated from an XSD element
type Medborgarskap struct {
	Status                string `xml:"status,attr"`
	MedborgarskapslandKod string `xml:"MedborgarskapslandKod"`
	Medborgarskapsdatum   int    `xml:"Medborgarskapsdatum"`
}

// Samordningsnummeruppgifter is generated from an XSD element
type Samordningsnummeruppgifter struct {
	Tilldelningsdatum                  int `xml:"Tilldelningsdatum"`
	PreliminartVilandeforklaringsdatum int `xml:"PreliminartVilandeforklaringsdatum"`
	Fornyelsedatum                     int `xml:"Fornyelsedatum"`
	DatumAvliden                       int `xml:"DatumAvliden"`
}

// Historik is generated from an XSD element
type Historik struct {
	Folkbokforing        []Folkbokforing      `xml:"Folkbokforing"`
	Folkbokforingsadress Folkbokforingsadress `xml:"Folkbokforingsadress"`
}

// Sarlosning is generated from an XSD element
type Sarlosning struct {
	SarInvandring        SarInvandring  `xml:"SarInvandring"`
	Utvandring           Utvandring     `xml:"Utvandring"`
	Avregistrering       Avregistrering `xml:"Avregistrering"`
	Beslutsgrund         string         `xml:"Beslutsgrund"`
	NamnIngivareDodsfall string         `xml:"NamnIngivareDodsfall"`
	Relationer           Relationer     `xml:"Relationer"`
}

// SarInvandring is generated from an XSD element
type SarInvandring struct {
	InvandringslandKod   string `xml:"InvandringslandKod"`
	InvandringsortNorden string `xml:"InvandringsortNorden"`
}

// Utvandring is generated from an XSD element
type Utvandring struct {
	UtvandringslandKod string `xml:"UtvandringslandKod"`
}
